version: '3.4'

services:
  moviedb:
    container_name: moviedb
    restart: always
    ports:
      - "1593:1593"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASSWORD}
    env_file:
      - .env

  movie.api:
    depends_on:
      - moviedb
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - PUBLIC_API_URL=http://localhost:8080
      - ConnectionStrings__Database=Server=moviedb;Database=MovieDb;User Id=sa;Password=${DB_PASSWORD};Encrypt=False;TrustServerCertificate=True
    ports:
      - "8080:8080"
    env_file:
      - .env

  movie.ui:
    depends_on:
      - movie.api
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:8081
      - ASPNETCORE_ENVIRONMENT=Docker 
      - ApiConfig__MovieApiBase=http://movie.api:8080/api/
      - ApiConfig__MovieApiVersion=v2
    ports:
      - "8081:8081"