version: '3.4'

services:
  moviedb:
    image: mcr.microsoft.com/mssql/server

  movie.api:
    image: ${DOCKER_REGISTRY-}movieapi
    build:
      context: .
      dockerfile: Movie.API/Dockerfile

  movie.ui:
    image: ${DOCKER_REGISTRY-}movieui
    build:
      context: .
      dockerfile: Movie.WebUI/Dockerfile